datafusion-contrib/datafusion-federation

examples/Cargo.toml
examples/examples/flight-sql.rs
sources/flight-sql/Cargo.toml
sources/flight-sql/src/executor/mod.rs

This PR adds support for the following FlightSQL features:
- Combining multiple streams in the case the returned Ticket has multiple endpoints 
- Support basic and PKI auth
I also attempting refactoring according to DataFusion's suggested practice when needing to call async methods within the execute method of a physical plan. As discussed on the prior PR, it is still painful to obtain the schema even when following this method. I do think it is slightly cleaner than `try_unfold` and can be cleaned up further if we figure out a better way to obtain the expected schema of the flight stream.

Support multiple FlightSQL Endpoints + Auth Options

---

sources/flight-sql/src/executor/mod.rs
sources/sql/src/connectorx/executor.rs
sources/sql/src/executor.rs
sources/sql/src/lib.rs
sources/sql/src/schema.rs

This PR simplifies FlightSQL Execution plans by relying on the VirtualExecutionPlan inferred from the sub-logical plan sliced out of the overall query to infer the schema. This avoids the need for block_on and simplifies the code further. 
Additionally, I added a new async trait method `get_table_schema` so SQLExecutors can implement arbitrary logic to return what the overall table schema of each table is.

Pass VirtualExecutionPlan Schema to SQLExecutors

---

sources/flight-sql/src/server/service.rs
sources/flight-sql/src/server/session.rs

Avoid unnecessary use of the DataFusion Result in the Flight SQL server example.

Simplify Flight SQL server error handling.

---

examples/examples/flight-sql.rs
examples/examples/sqlite-partial.rs
examples/examples/sqlite.rs
sources/flight-sql/src/executor/mod.rs
sources/sql/src/connectorx/executor.rs
sources/sql/src/executor.rs
sources/sql/src/schema.rs

I extended the `SQLExecutor` trait to also list available tables. No implementations for now.

Add table inference and allow schema injection.

---

Cargo.toml
sources/flight-sql/Cargo.toml
sources/flight-sql/src/server/service.rs

This PR implements initial minimal support for  executing a substrait plan via DataFusion on the FlightSQL server.

Intial support for substrait on flightsql server

---

examples/Cargo.toml
examples/examples/postgres-partial.rs
sources/flight-sql/src/executor/mod.rs
sources/sql/src/connectorx/executor.rs
sources/sql/src/executor.rs
sources/sql/src/lib.rs
sources/sql/src/producer.rs
sources/sql/src/schema.rs

Federation wasn’t working with the Postgres dialect and ConnectorX was crashing on an example using postgres, so this PR adds fixes for both of these issues.
The dialect parameter will allow future extensibility to other dialects for query generation.

feat: add support for producing SQL in multiple dialects

---

datafusion-federation/src/plan_node.rs
examples/examples/sqlite.rs
sources/sql/src/lib.rs

I wanted an easy way to be able to quickly check what SQL is actually being sent to a remote SQLExecutor, as well as the logical plan that was being federated.
Ideally we could have more information about the compute context at the LogicalPlan level, but I'm not 100% sure what makes sense yet.
Sample output:
`EXPLAIN="true" cargo run --example sqlite`
```
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan …
```

fix: adds more information when an `EXPLAIN <query>` is run on a federated source

---

datafusion-federation/src/analyzer.rs

Relaxes `get_table_source` called in `get_federation_provider` to allow TableScans of non-federated tables.
The optimizer already handles this case with:
```rust
// Check if this node determines the FederationProvider
let sole_provider = self.get_federation_provider(plan)?;
if sole_provider.is_some() {
return Ok((None, sole_provider)); // <-- Federated TableScans return Some
}
// optimize_inputs
let inputs = plan.inputs();
if inputs.is_empty() {
return Ok((None, None)); // <-- Will mark this TableScan as non-federated by returning None
}
```

feat: allow TableScans of non-federated sources

---

datafusion-federation/src/table_provider.rs

Adds a fallback TableProvider that can be used in DataFusion contexts without the federation optimizer in-use, which provides a graceful fallback mechanism.

feat: add fallback TableProvider to FederatedTableProviderAdaptor

---

datafusion-flight-sql-server/Cargo.toml
datafusion-flight-sql-server/src/service.rs

FlightSQL has a set of commands to interrogate the server for information about the available catalogs, db schemas, tables, and table types. This change implements those four commands in terms of a datafusion context.

feat: implement catalog/schema/table commands on the service

---

datafusion-flight-sql-server/src/service.rs

This change enables consumers of the server to specify which SQLOptions they want to use to verify any SQL queries before they are run.

feat: expose SQLOptions on server

---

datafusion-federation/src/schema_cast/mod.rs

[EnforceDistribution PhisicalOptimizerRule](https://github.com/apache/datafusion/blob/9df957b63ea4c9fb787c6f9a3c15d1dcd394ac72/datafusion/core/src/physical_optimizer/enforce_distribution.rs#L189) aggressively enforces inputs to be split and processed in parallel which leads to re-ordering of record batches containing few records.
`benefits_from_input_partitioning` setting enforces 1-1 relationship between `SchemaCastScanExec` and its input preventing re-ordering. This does not block partitioning/parallel processing in general, just ensures 1-1 mapping for SchemaCastScanExec and wrapped input.
Example plan. `RepartitionExec` is automatically enforced by the optimization. Order of resultant records batches vary as query records are processed in parallel.
```console …
```

Preserve records batch order when SchemaCastScanExec is involved

---

datafusion-federation/src/schema_cast/lists_cast.rs
datafusion-federation/src/schema_cast/record_convert.rs
datafusion-federation/src/schema_cast/struct_cast.rs

This PR addresses an issue in the MySQL implementation within the datafusion-table-providers project. In the MySQL implementation, varchar and json types are mapped to DataFusion's LargeUtf8 type, corresponding to the LargeString data type. In the test code of datafusion-table-providers, the try_cast_to function is used to convert the record batch from a query according to the schema used during table creation. However, the previous version only supported String and could not convert record batches from MySQL where json uses LargeString. This PR adds support for LargeString to enable the conversion of such record batches.

feat: add support for converting LargeUtf8/LargeString in try_cast_to

---

datafusion-federation/src/lib.rs

Default session state should include default features, otherwise some basic aggregation function (e.g., `Count`) will not be supported:
```rust
let state = datafusion_federation::default_session_state();
let ctx = SessionContext::new_with_state(state);
let query = r#"SELECT COUNT(*) FROM hits"#;
let df = ctx.sql(query).await?;
```
will panic:
```
No candidates provided.
stack backtrace:
0: rust_begin_unwind
at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/std/src/panicking.rs:665:5
1: core::panicking::panic_fmt
at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/core/src/panicking.rs:74:14
2: core::panicking::panic_display
at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/core/src/panicking.rs:264:5
3: core::option::expect_failed
at …
```

Default session state should include default features

---

datafusion-flight-sql-server/src/service.rs

With flight_info requests the returned schema needs to exactly match the encoded flight data. The FlightDataEncoder will change the schema in order to hydrate dictionaries. This means the schema reported from flight_info requests did not match the encoded data.
This change copies the logic from arrow-flight that can transform a schema for hydrated dictionaries. See
https://github.com/apache/arrow-rs/issues/6672 where the copied logic may be exposed directly.

fix: report hydrated schemas from flight_info requests

---

.github/dependabot.yml
.github/workflows/release_plz.yml

Hello,
This PR addresses issue #72. We still need to modify the repository settings to grant permission to the GitHub Action for creating/deleting PRs and also add the token for deployment to crates.io, as shown in steps 1 and 2 of this [quickstart guide](https://release-plz.ieni.dev/docs/github/quickstart#1-change-github-actions-permissions).
Thanks

Automate deployment using release_plz

---

.github/workflows/release_plz.yml
.release-plz.toml

This PR also remove the old PRs created by release_plz

github/workflows/release_plz: ignore flight-sql-table-provider crate

---

Cargo.toml
datafusion-flight-sql-server/src/service.rs

With this change we can delete the duplicated code from the FlightDataEncoder to determine the hydrated schema and instead use the known_schema method.
Fixes: #77

fix: use new known_schema api of FlightDataEncoder

---

datafusion-flight-sql-server/Cargo.toml

According to [substrait-rs documentation](https://github.com/substrait-io/substrait-rs/blob/main/CONTRIBUTING.md?plain=1#L52):
> In environments where no `protoc` is available the `protoc` feature can
> be enabled to build `protoc` from source:

flight-sql-server: Add `protoc` as feature in Cargo.toml when building substrait dependency

---

.gitignore
datafusion-federation/src/sql/analyzer.rs
datafusion-federation/src/sql/ast_analyzer.rs
datafusion-federation/src/sql/executor.rs
datafusion-federation/src/sql/mod.rs
datafusion-federation/src/sql/schema.rs
datafusion-federation/src/sql/table.rs
datafusion-federation/src/sql/table_reference.rs

Required for [this issue](https://github.com/datafusion-contrib/datafusion-table-providers/issues/301)
This PR primarily aims to refactor the SQL implementation and additionally define/extend types and traits  to support parameterized view.
The idea behind the change is essentially separating SQLExecutor behavior from Table. Allowing tables to define their own state and make changes to logical/ast accordingly.  Things like handling 4 token multi-part identifiers, attaching WITH context ..etc can be done via creating a custom `SQLTable` implementation in datafusion-table-provider.
- Adds `SQLTable` trait which is used by `SQLTableSource`. `SQLTable` trait abstracts information about the remote table and allows implementors of the trait to hook into the final stages of federation, where …

Refactor the SQL implementation to include the `SQLTable` trait and add support for parameterized views.

---

datafusion-federation/src/sql/analyzer.rs
datafusion-federation/src/sql/ast_analyzer.rs
datafusion-federation/src/sql/mod.rs
datafusion-federation/src/sql/table.rs
datafusion-federation/src/sql/table_reference.rs

The `sql` feature was not being tested, meaning some errors were hidden from testing.

Fix errors in the `sql` feature

---

.github/dependabot.yml

Re-add .github/dependabot.yml to keep GitHub Actions up to date, it does not update Cargo dependencies.

Keep the actions up-to-date

---

datafusion-federation/src/plan_node.rs
datafusion-federation/src/sql/mod.rs

This PR tries to fix some blockers that are observed while rewriting federated logical plan. See https://github.com/datafusion-contrib/datafusion-federation/issues/129#issuecomment-3042336340

Expose some types and fields to public
